=== lhill7/COMP336/COMP336/recipebook.dtd
<!--
RecipeXML Revamped
-->
<?xml-stylesheet type="text/xsl" href="RecipeBook.xsl"?>
<!-- === Hyperlinks for URL references === -->
<!ELEMENT hyperlink (#PCDATA)>
<!ATTLIST hyperlink
	url CDATA #REQUIRED
>
<!-- === Information about a recipe === -->
<!ELEMENT author (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT course (#PCDATA)>
<!ELEMENT type (sweet, spicy, bland, sour, rich)>
<!ELEMENT sweet (#PCDATA)>
<!ELEMENT spicy (#PCDATA)>
<!ELEMENT bland (#PCDATA)>
<!ELEMENT sour (#PCDATA)>
<!ELEMENT rich (#PCDATA)>
<!ELEMENT preptime (#PCDATA)>
<!ELEMENT source (#PCDATA | hyperlink)*>
<!-- === Lists of ingredients === 
The substitution and non substitution elements describe ingredients that can be used in lieu of the ingredients originally listed 	and ones that can't, or rather shouldn't, be used.  
-->
<!ELEMENT ingredients (substiution, non_substituion, quantity, unit)>
<!ELEMENT fooditem (#PCDATA)>
<!ELEMENT substitution (#PCDATA)>
<!ELEMENT non_substitution (PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT unit (#PCDATA)>
<!ELEMENT budget (#PCDATA)>
<!-- Might add an attribute value to more specifically define unit measurements later -->


<!-- === Elements of preparation ===
The equipment tag refers to the types of pots, pans, utensils, etc. that the person will need to cook. The step tag is pretty self explanatory. 
 -->
<!ELEMENT equipment (#PCDATA | hyperlink)*>
<!ELEMENT step (#PCDATA | equipment | hyperlink)*>

<!-- === The main elements of a recipe === -->
<!ELEMENT title (#PCDATA)>
<!ELEMENT recipeinfo (author | description | course | type | preptime | source | serving)*>
<!ELEMENT ingredientlist (ingredient)*>
<!ELEMENT preparation (#PCDATA | equipment | step | hyperlink)*>
<!ELEMENT notes (#PCDATA | hyperlink)*>

<!-- === And finally, the recipe itself === -->
<!ELEMENT recipe (title, recipeinfo?, ingredientlist, preparation, serving?, notes?)>

<!-- === A section provides logical divisions of a cookbook === -->
<!ELEMENT section (title, recipe+)>
<!-- === A cookbook consists of one or more recipes or sections === -->
<!ELEMENT cookbook (title, (section | recipe)+)>

=== lhill7/COMP336/COMP336/15_Minute_Brownies.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2012 rel. 2 sp1 (http://www.altova.com)-->
<!DOCTYPE cookbook SYSTEM "C:\Users\Lyness\Desktop\recipebook.dtd">
<cookbook>
	<title>Snacks on Snack on Snacks</title>
	<section>
		<title>Desserts</title>
		<recipe>
			<title>15 Minute Brownies</title>
			<recipeinfo>
				<author>sooz</author>
			</recipeinfo>
			<ingredientlist/>
			<preparation>
				<equipment>
					<hyperlink url="text">text</hyperlink>
				</equipment>
				<step>1. Combine flour, soda and salt; set aside.
					<equipment>mixing bowl
						<hyperlink url="text">text</hyperlink>
					</equipment>
					<hyperlink url="text">text</hyperlink>
				</step>
				<step> 2. In microwave-safe mixing bowl, combine butter, sugar and water. Cook for
  2 minutes at 100% power, stirring after 1 minute. Remove from oven.Add 1
  cup chocolate chips and vanilla and stir until smooth and chips are melted.
					<equipment>see previous
						<hyperlink url="text">text</hyperlink>
					</equipment>
					<hyperlink url="text">text</hyperlink>
				</step>
				<step>3. Add eggs, one at a time, beating after each addition. Blend in flour
  mixture and stir in remaining chocolate chips.
					<equipment>see previous
						<hyperlink url="text">text</hyperlink>
					</equipment>
					<hyperlink url="text">text</hyperlink>
				</step>
				<step>4. Pour into an 8 or 9 inch microwave-safe baking pan. Place a saucer,
  upside down, in the microwave and put baking pan on top of saucer.
					<equipment>baking pan; saucer
						<hyperlink url="text">text</hyperlink>
					</equipment>
					<hyperlink url="text">text</hyperlink>
				</step>
				<step> 5. Cook at 70% power for 10 minutes turning after 5 minutes. Enjoy!
					<equipment>
						<hyperlink url="text">text</hyperlink>
					</equipment>
					<hyperlink url="text">text</hyperlink>
				</step>
				<hyperlink url="text">text</hyperlink>
			</preparation>
			<notes>
				<hyperlink url="text">text</hyperlink>
			</notes>
		</recipe>
	</section>
</cookbook>

=== lhill7/COMP336/COMP336/Chocolate_Covered_Strawberries.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2012 rel. 2 sp1 (http://www.altova.com)-->
<!DOCTYPE cookbook SYSTEM "recipebook.dtd">
<cookbook>
	<title>Snacks on Snacks on Snacks</title>
	<section>
		<title>Dessert</title>
		<recipe>
			<title>Chocolate Covered Cherry Cookies</title>
			<recipeinfo>
				<author>Linda Place</author>
			</recipeinfo>"Christmas and chocolate-covered cherries are forever
  entwined in my mind and memories. Not the expensive department store kind,
  mind you, with their dark bitter chocolate and runny syrup, but your basic
  Brach's. Each Christmas found the coveted white box stretching my stocking,
  two layers of cream-filled heaven with a cherry floating therein--and no
  requirement to share them with anyone.
			<ingredientlist/>Flour; Unsweetened Cocoa Powder; Salt; Baking Powder; Baking Soda; Butter; Sugar; Egg; Vanilla; Frosting; Semi-Sweet Chocolate Chips; Marachino Cherry's; Sweetend Condensed Milk; Cherry Juice
			<preparation>10 Minutes 
				<equipment>Bowl; Egg Beater; Cookie Sheet; Medium Saucepan
					<hyperlink url="text">text</hyperlink>
				</equipment>
				<step>1. In bowl, stir together flour, cocoa, salt, baking powder and baking
  soda. In another bowl, beat butter and sugar until fluffy. Add egg and
  vanilla to butter-sugar mixture and beat well. Gradually add dry
  ingredients to butter-sugar mixture and beat until well blended.<br />
  
    2. Shape dough into 1-inch balls. Place on ungreased cookie sheet and
  push down center of each ball with thumb. Drain cherries and reserve juice.
  Place 1 cherry in center of each indentation. Heat oven to 350 degrees.<br />
  
    3. For frosting, put chocolate chips and sweetened condensed milk in
  small saucepan. Heat until chocolate melts. Stir in 4 teaspoons cherry
  juice.  If too thick, add more juice. <br/>
  
    4. Spoon 1 teaspoon frosting over each cherry. Spread to cover cherry.
  Bake 10 minutes or until done. Do not overcook. Remove to wire rack and
  cool.  The cookies freeze nicely.
  <br />
					<equipment>
						<hyperlink url="text">text</hyperlink>
					</equipment>
					<hyperlink url="text">text</hyperlink>
				</step>
				<hyperlink url="text">text</hyperlink>
			</preparation>Preperation Time: 45 minutes
			<notes>
				<hyperlink url="text">text</hyperlink>
			</notes>
		</recipe>
	</section>
</cookbook>
